# make some exercises using CLI

name: exercise-cli-github 

on: workflow_dispatch
env:
  GH_TOKEN: ${{ github.token }}

jobs:
  exercises-with-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Determine workflow list
        run: |
          gh workflow list --all > workflow_list.txt
      - name: Upload workflow list file
        uses: actions/upload-artifact@v4
        with:
          name: workflow-list
          path: workflow_list.txt
      - name: Determine active workflows
        run: bash ./.github/scripts/filter_active_workflows.sh
      - name: xxx
        run: echo "${active_workflows[@]}"
