# make some exercises using CLI

name: exercise-cli-github 

on: workflow_dispatch
env:
  GH_TOKEN: ${{ github.token }}

jobs:
  exercises-with-workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          gh workflow list --all > workflow_list.txt
      - uses: actions/upload-artifact@v4
        name: Upload workflow list file
        
