# make some exercises using CLI

name: exercise-cli-github 

on: workflow_dispatch
env:
  GH_TOKEN: ${{ github.token }}

jobs:
  exercises-with-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Determine workflow list
        run: gh workflow list --all > workflow_list.txt
      - name: Upload workflow list file
        uses: actions/upload-artifact@v4
        with:
          name: workflow-list
          path: workflow_list.txt
      - name: Determine active workflows
        id: determine-active-workflows
        run: |
          active_workflows=()

          while read name state id; do
              if [[ $name == "exercise-cli-github" ]]; then
                  continue
              elif [[ $state == "active" ]]; then
                  active_workflows+=("$name")
              else
                  continue
              fi
          done < workflow_list.txt

          echo "ACTIVE_WORKFLOWS=${active_workflows[@]}" >> "$GITHUB_OUTPUT"
      - name: List active workflows
        run: |
          echo "${{ steps.determine-active-workflows.outputs.ACTIVE_WORKFLOWS }}"
          
          read -a active_workflows <<< "${{ steps.determine-active-workflows.outputs.ACTIVE_WORKFLOWS }}"

          for active_workflow in ${active_workflows[@]}"; do
            echo $active_workflow
          done







