name: List-workflows-(GitHubCLI)

on: workflow_dispatch

env:
  GH_TOKEN: ${{ github.token }}
permissions: read-all
  
jobs:
  list-workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gh workflow list
