# list all repositories using CLI

name: list-repos-cli

on: workflow_dispatch
env:
  GH_TOKEN: ${{ github.token }}
permissions: read-all

jobs:
  list-repos:
    runs-on: ubuntu-latest
    steps:
      - run: gh repo list
