name: List workflows (GitHub CLI)

on: workflow_dispatch

#env:
#  GH_TOKEN: ${{ github.token }}
permissions: read-all
  
jobs:
  list-workflows:
    runs-on: ubuntu-latest
#    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - run: gh workflow list
