# list branches in a GitHub repo per Python script
name: list-branches
on: push
jobs:
  list-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: ./.github/scripts/ListBranches.py
        shell: bash
