# list branches in a GitHub repo per Python script
name: list-branches
on: push
jobs:
  list-branches:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: run python script
        run: |
          python ./.github/scripts/ListBranches.py
