name: Test workflow
run-name: Das ist ein Testworkflow von ${{ github.actor }}
on: push
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo ${{github.workflow}}
          echo ${{job.status}}

